### ISSUE TITLE
New Website Redesign Broke RSS Feeds

### ISSUE THREAD

**Issue by mattdep** [jullrich/ISC-Bugs#80]
The RSS feed no longer works correctly and points to the old location vs the new.

https://isc.sans.edu/diary/rss/28828 (old)
https://isc.sans.edu/forums/diary/7Zip+Editing+MoW/ (new)

**Comment by ChaosAdventurer** [comment]
This would also affect all existing links out there to specific diaries,  aka Link Rot
What would really help across the board is a redirection piece that accepts the old URL and redirects it to the new.  
This is something we've done on the Micro Focus Community as they were migrated together to make it seamless for all.

**Comment by mattdep** [comment]
I'm specifically talking about newly published diary entries and not link rot.  The links in the RSS file point to the old location.

RSS File:
https://isc.sans.edu/rssfeed.xml

Today's diary post titled "Excel 4 Emotet Maldoc Analysis using CyberChef, (Sun, Jul 10th)" points to: 
https://isc.sans.edu/diary/rss/28830

The correct location is:
https://isc.sans.edu/forums/diary/Excel+4+Emotet+Maldoc+Analysis+using+CyberChef/28830/

Hope that helps.

**Comment by mattdep** [comment]
It appears the "Handler's Diary (Full text)" feed is affected as well:

https://isc.sans.edu/rssfeed_full.xml

**Comment by ChaosAdventurer** [comment]
Since it isn't just new links that don't work, but also the old ones that many will have used in their own blogs, documentation, saved links, etc.   Link Rot is a related part of the problem that might point to a more comprehensive fix.

Just a few of [my saved links ](https://www.konecnyad.ca/chaosadventurer/bmsecrty.htm)that are no longer working 
that shows this isn't just the RSS feed that is still feeding the old format

https://isc.sans.edu/diary/Critical+Security+Controls%3A+Getting+to+know+the+unknown/20517
https://isc.sans.edu/diary/Effective+security+governance/22360
https://isc.sans.edu/diary/rss/26404
https://isc.sans.edu/diary/SSLTLS+on+port+389.+Say+what%3F/22135
https://isc.sans.edu/diary/rss/25610

so how am I going to figure out the replacement links now?  Google isn't going to help on this.

A whole pile of useful information has now disappeared from the internet with this lack of a redirect for old links that parts of the site is still using as well.  Proper redirects solve both symptoms of this problem.

**Comment by jullrich** [comment]
made a first fix live. still need to fully validate it. (there may still be some caching happening)

**Comment by ChaosAdventurer** [comment]
So much better, that did the trick
The only related broken link I have is Ouch! no longer being at securingthehuman.sans.org but I found its new home at www.sans.org/newsletters/ouch/ and I am updating my links accordingly.

**Comment by mattdep** [comment]
Both issues appear to be resolved.  Thank you!
